# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35bbf954e3ffd855bc15b2f129f74ec722f25723acc277b8c592a353f63af0dc128c0c309a9d91b3a421baa34d2c495a249e8665daa854e72f54026f7f5c16e6

test:
  secret_key_base: ee3371e808fda545f8ac263915d0716a5ccf70742d2b0a7fc1941c56707bc22b130b6d74cf7541f363c8da7d362c47d942e54afa92bbf036c864ce3cae9fa533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
